#ifndef FIRMWARE_VERSION_H
#define FIRMWARE_VERSION_H

#define FIRMWARE_VERSION_MAJOR 0U
#define FIRMWARE_VERSION_MINOR 8U
#define FIRMWARE_VERSION_PATCH 0U

#define FIRMWARE_VERSION_STRING "0.8.0-rc.2"
#define FIRMWARE_USB_BCD_DEVICE  0x0080U

#endif
